# Generated by Django 5.1.2 on 2024-12-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('dis', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('off_price', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField()),
                ('img', models.FileField(upload_to='')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
