# Generated by Django 5.1.4 on 2025-01-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='p_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='s_size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
